language: node_js

node_js:
  - node

install: 
 - npm install

services:
 - postgresql

before_script:
 - psql -c "CREATE DATABASE testDatabase;" -U postgres
 - psql -c "CREATE USER postgres WITH PASSWORD 'ibombe';" -U postgres

script:
  - npm test
  
after_success:
- npm run coveralls
