language: node_js
git:
  depth:       3
node_js:
  - "10"
install: npm install
cache:
  directories:
    - node_modules
addons:
 postgresql: "9.6"

services:
 - postgresql

before_script:
 - psql -c 'CREATE DATABASE FreeMentorsTest;' -U postgres
script:
  - npm test
after_success:
- psql -c'	
- npm run coveralls
notifications:
email: false