services:
 - postgresql

 language:      node_js

node_js:
  - "10"
install:       npm install
cache:
  directories:
    - node_modules
addons:
 postgresql: "9.6"


before_install:
 - psql -c 'create database FreeMentorsTest;' -U postgres
script:
  - npm test
after_success:
- npm run coveralls

notifications:
email: false