const users = [
  {
    userId: 1,
    firstName: 'Im',
    lastName: 'Admin',
    email: 'johndoe1@email.com',
    password: '$2b$10$aVL6hs6.I5z11JJLDHIu2eaZZsod54V465LM7qe8LBuiGFy123jbO',
    address: 'Nairobi Kenya',
    bio: 'rapper, record producer, and actor who was known as one of the most-controversial and best-selling artists of the early 21st century',
    occupation: 'Musician',
    expertise: 'rapping',
    isMentor: true,
    isAdmin: true,
  },
  {
    userId: 2,
    firstName: 'ImA',
    lastName: 'Mentor',
    email: 'johndoe2@email.com',
    password: '$2b$10$aVL6hs6.I5z11JJLDHIu2eaZZsod54V465LM7qe8LBuiGFy123jbO',
    address: 'Nairobi Kenya',
    bio: 'rapper, record producer, and actor who was known as one of the most-controversial and best-selling artists of the early 21st century',
    occupation: 'Musician',
    expertise: 'rapping',
    isMentor: true,
    isAdmin: false,
  },
  {
    userId: 3,
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe3@email.com',
    password: '$2b$10$aVL6hs6.I5z11JJLDHIu2eaZZsod54V465LM7qe8LBuiGFy123jbO',
    address: 'Nairobi Kenya',
    bio: 'rapper, record producer, and actor who was known as one of the most-controversial and best-selling artists of the early 21st century',
    occupation: 'Musician',
    expertise: 'rapping',
    isMentor: false,
    isAdmin: false,
  },
  {
    userId: 4,
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe4@email.com',
    password: '$2b$10$aVL6hs6.I5z11JJLDHIu2eaZZsod54V465LM7qe8LBuiGFy123jbO',
    address: 'Nairobi Kenya',
    bio: 'rapper, record producer, and actor who was known as one of the most-controversial and best-selling artists of the early 21st century',
    occupation: 'Musician',
    expertise: 'rapping',
    isMentor: false,
    isAdmin: false,
  }

];

export default users;
